version: "3.9"

services:
  account_service:
    build: ./account_service
    container_name: account_service
    restart: unless-stopped
    ports:
      - "3003:3003"
    environment:
      - PORT=3003
    networks:
      - micro_net

networks:
  micro_net:
    driver: bridge