events {}

http {
    upstream user_backend {
        server user_service_1:3001;
        server user_service_2:3001;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://user_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}