worker_processes auto;

events {
    worker_connections 1024;
}

http {
    sendfile on;
    keepalive_timeout 65;

    # ─────────────────────────
    # USER SERVICE (port 3001)
    # ─────────────────────────
    upstream user_service {
        server user_service_1:3001;
        server user_service_2:3001;
        server user_service_3:3001;
    }

    # ─────────────────────────
    # ACCOUNT SERVICE (port 3003)
    # ─────────────────────────
    upstream account_service {
        server account_service1:3003;
        server account_service2:3003;
        server account_service3:3003;
    }

    # ─────────────────────────
    # NOTIFICATION SERVICE (port 3002)
    # ─────────────────────────
    upstream notification_service {
        server notification_service1:3002;
        server notification_service2:3002;
        server notification_service3:3002;
    }

    # ─────────────────────────
    # TRANSFERT SERVICE (port 3004)
    # ─────────────────────────
    upstream transfert_service {
        server transfert_service1:3004;
        server transfert_service2:3004;
        server transfert_service3:3004;
    }

    # ─────────────────────────
    # ROUTAGE API (reverse proxy)
    # ─────────────────────────
    server {
        listen 80;
        server_name _;

        # USER SERVICE
        location /users/ {
            proxy_pass http://user_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # AUTH (user_service)
        location /auth/ {
            proxy_pass http://user_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # ACCOUNT SERVICE
        location /accounts/ {
            proxy_pass http://account_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # NOTIFICATION
        location /notifications/ {
            proxy_pass http://notification_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # TRANSFERT
        location /transferts/ {
            proxy_pass http://transfert_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}